{% set name = "libcifpp" %}
{% set version = "10.0.0" %}
{% set sha256 = "6c6044e7f92273fd0c75e7921bf7692732608c273894464c982e514b92b90945" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PDB-REDO/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - eigen
    - fast_float  # [osx]
    # Use the version pinned in conda-forge
    - libboost-devel ==1.86.0  # [linux]
    - pcre2
    - sqlite
    - zlib

test:
  commands:
    - test -e ${PREFIX}/lib/libcifpp.so  # [linux]
    - test -e ${PREFIX}/lib/libcifpp.dylib  # [osx]

about:
  home: "https://github.com/PDB-REDO/libcifpp"
  license: "BSD-2-Clause"
  license_file: LICENSE
  license_family: BSD
  summary: "Library containing code to manipulate mmCIF and PDB files."
  doc_url: "https://pdb-redo.github.io/libcifpp"
  dev_url: "https://github.com/PDB-REDO/libcifpp"
  description: |
    This library, libcifpp, is a generic CIF library with some specific additions to work with mmCIF files.
    The main focus of this library is to make sure that files read or written are valid.
    That is, they are syntactically valid and their content is valid with respect to a CIF dictionary, if such a dictionary is available and specified.

extra:
  recipe-maintainers:
    - multimeric
  additional-platforms:
    - linux-aarch64
    - osx-arm64
