{% set name = "acedrg" %}
{% set version = "8e54f9b" %}

package:
  name: acedrg
  version: 8e54f9b

source:
  git_url: https://ccp4forge.rc-harwell.ac.uk/ccp4/acedrg.git
  git_rev: 8e54f9b

build:
  number: 0
  run_exports: {{ pin_subpackage(name, exact=True) }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - pkg-config
  host:
    - python
  run:
    - python
    - rdkit

# test:
#   commands:
#     - acedrg --help || true
#     - libmol --help || true
#   requires:
#     - pytest

about:
  home: https://ccp4forge.rc-harwell.ac.uk/ccp4/acedrg
  dev_url: https://ccp4forge.rc-harwell.ac.uk/ccp4/acedrg
  doc_url: https://ccp4.github.io/acedrg/
  license: UNKNOWN
  license_family: OTHER
  summary: "ACEDRG: ligand/monosaccharide building and restraint generation tools from CCP4"
  description: |
    ACEDRG is a tool for generating ligand and monosaccharide coordinates and
    restraint dictionaries for macromolecular crystallography. It is part of the
    Collaborative Computational Project Number 4 (CCP4) software suite.

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1107/S2059798317000067
  recipe-maintainers:
    - eunos-1128
