{% set name = "FTDMP" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kliment-olechnovic/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3c42a02591b388c3c8bf8b640fccefb4c0bc6201158e7226260defd65022dfe9

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  run:
    - cuda-runtime ==12.1.0  # [linux]
    - cuda-toolkit ==12.1.0  # [linux]
    - openmm
    - pandas
    - pdbfixer
    - pyg-lib  # [linux]
    - python
    - pytorch ==2.1.0  # [linux]
    - r
    - torchvision  # [linux]
    - torchaudio  # [linux]
    - torch-geometric  # [linux]
    - torch-scatter  # [linux]
    - torchsparse  # [linux]
    - pytorch_cluster  # [linux]
    - torch_spline_conv  # [linux]

test:
  commands:
    - ftdmp-all -h

about:
  home: https://kliment-olechnovic.github.io/ftdmp
  dev_url: https://github.com/kliment-olechnovic/ftdmp
  doc_url: https://kliment-olechnovic.github.io/ftdmp
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Running docking experiments and scoring/ranking multimeric models"
  description: |
    FTDMP is a software system for running docking experiments and scoring/ranking multimeric models.

    FTDMP was used in CASP15 by the "Venclovas" team (Vilnius University / Life Sciences Center / Institute of Biotechnology).
    The most novel and useful features of FTDMP are integrated VoroIF-jury and VoroIF-GNN methods.

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - doi:10.1002/prot.26792
  recipe-maintainers:
    - eunos-1128
