{% set version = "1.3.1" %}
{% set beta_suffix = "" %}
{% set sha256 = "c798011348ae0094ea821790a6fcfca9c2180aadb0ca0df61e5a43531da9a25d" %}

package:
  name: hmftools-neo
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/neo-v{{ version }}/neo_v{{ version }}{{ beta_suffix }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage("hmftools-neo", max_pin="x.x") }}

requirements:
  run:
    - openjdk >=8,<=21

test:
  commands:
    - 'neo -version | grep "Neo version"'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/neo
  license: GPL-3.0-only
  license_family: GPL
  summary: Identification of neoepitope and calculation of allele specific neoepitope binding and presentation likelihood.
