{% set name = "PLINDER" %}
{% set version = "1.0.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plinder-${{ version }}.tar.gz
  sha256: 48f6669eece102b9540b7460196d552e2a7ffbd0cc0e0b35e0751b6547ad8789

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - plinder_download = plinder.core.index.utils:download_plinder_cmd
    - plinder_eval = plinder.eval.cli:main
    - plinder_prepare_release = plinder.data.pipeline.public_release:main
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x.x") }}

requirements:
  host:
    - python {{ python_min }}.*
    - python-build
    - setuptools
    - setuptools-scm
    - pip
  run:
    - __unix
    - python >={{ python_min }}

    # Core runtime dependencies
    - biotite >=1.2
    - numpy
    - threadpoolctl >=3.6
    - pandas
    - pydantic
    - tqdm
    - peppr >=0.13
    - voronotalt >=1.1
    - rdkit >=2025.09.1
    - pyarrow
    - omegaconf
    - python-duckdb >=1.5
    - cloudpathlib >=0.25,<0.26
    - requests

    # Dependencies for data generation
    - google-cloud-storage
    - gcsfs
    - numba
    - mmseqs2
    - foldseek
    - networkit >11.0
    - tabulate
    - mmpdb >=3.1.4,<3.2
    - ligand-validation ==0.0.1

    # Dependencies for evaluation, loading, and plotting
    - openstructure >=2.12.0
    - posebusters >=0.6.5
    - pytorch-cpu
    - matplotlib-base
    - seaborn
    - mols2grid
    - matplotlib-venn
    - scipy

test:
  imports:
    - plinder
  commands:
    - plinder_download --help
    - plinder_eval --help
    - plinder_prepare_release --help
  pip_check: true

about:
  summary: "PLINDER: Protein & Ligand INteraction Dataset and Evaluation Resource"
  description: |
    Protein-ligand interactions are foundational to the understanding of science and discovery of therapies.
    However, to this date, no large, high quality datasets with real-life relevant evaluations exist.

    PLINDER is an academic-industry collaboration to address this, driven by VantAI, NVIDIA, the Computational Structural Biology group at the University of Basel & SIB Swiss Institute of Bioinformatics - co-organizers of CASP, and MIT.
    We aim to provide a gold standard dataset and evaluations to push the field of computational protein-ligand interactions prediction forward.
  home: "https://www.plinder.sh"
  dev_url: "https://github.com/plinder-org/plinder"
  doc_url: "https://plinder-org.github.io/plinder"
  license: "MIT AND Apache-2.0"
  license_file:
    - NOTICE
    - LICENSE.txt

extra:
  identifiers:
    - doi:10.1101/2024.07.17.603955
  recipe-maintainers:
    - eunos-1128
